// This is auto-generated by Datastar. DO NOT EDIT.

namespace StarFederation.Datastar

open System

type ElementMergeMode =
/// Morphs the element into the existing element using Datastar&#39;s morphing, preserving focus and minimizing element changes.
| Outer
/// Morphs the element into the innerHTML using Datastar&#39;s morphing, preserving focus and minimizing element changes.
| Inner
/// Removes the existing element from the DOM.
| Remove
/// Prepends the element inside the existing element.
| Prepend
/// Appends the element inside the existing element.
| Append
/// Inserts the element before the existing element.
| Before
/// Inserts the element after the existing element.
| After

type EventType =
/// An event for merging HTML elements into the DOM.
| MergeElements
/// An event for merging signals.
| MergeSignals
/// An event for executing &lt;script/&gt; elements in the browser.
| ExecuteScript


module Consts =
    let [<Literal>] DatastarKey               = "datastar"
    let [<Literal>] Version                   = "1.0.0-beta.11"

    /// Default: TimeSpan.FromMilliseconds 1000
    let DefaultSseRetryDuration = TimeSpan.FromMilliseconds 1000


    /// Default: outer - Morphs the element into the existing element using Datastar&#39;s morphing, preserving focus and minimizing element changes.
    let DefaultElementMergeMode = Outer

    let [<Literal>] DefaultElementsUseViewTransitions = false
    let [<Literal>] DefaultMergeSignalsOnlyIfMissing = false
    let [<Literal>] DefaultExecuteScriptAutoRemove = true

    let [<Literal>] DefaultExecuteScriptAttributes = "type module"

    let [<Literal>] DatastarDatalineSelector = "selector"
    let [<Literal>] DatastarDatalineMergeMode = "mergeMode"
    let [<Literal>] DatastarDatalineElements = "elements"
    let [<Literal>] DatastarDatalineUseViewTransition = "useViewTransition"
    let [<Literal>] DatastarDatalineSignals = "signals"
    let [<Literal>] DatastarDatalineOnlyIfMissing = "onlyIfMissing"
    let [<Literal>] DatastarDatalineScript = "script"
    let [<Literal>] DatastarDatalineAttributes = "attributes"
    let [<Literal>] DatastarDatalineAutoRemove = "autoRemove"

    module ElementMergeMode =
        let toString this =
            match this with
                | ElementMergeMode.Outer -> "outer"
                | ElementMergeMode.Inner -> "inner"
                | ElementMergeMode.Remove -> "remove"
                | ElementMergeMode.Prepend -> "prepend"
                | ElementMergeMode.Append -> "append"
                | ElementMergeMode.Before -> "before"
                | ElementMergeMode.After -> "after"

    module EventType =
        let toString this =
            match this with
                | EventType.MergeElements -> "datastar-merge-elements"
                | EventType.MergeSignals -> "datastar-merge-signals"
                | EventType.ExecuteScript -> "datastar-execute-script"