// This is auto-generated by Datastar. DO NOT EDIT.

using System.ComponentModel;
using NetEscapades.EnumGenerators;

namespace StarFederation.Datastar.Enumerations;

/// <summary>
///     Represents the different modes of merging fragments.
/// </summary>
[EnumExtensions]
public enum FragmentMergeMode
{
    /// <summary>
    ///     Morphs the fragment into the existing element using idiomorph.
    /// </summary>
    [Description("morph")]
    Morph,

    /// <summary>
    ///     Replaces the inner HTML of the existing element.
    /// </summary>
    [Description("inner")]
    Inner,

    /// <summary>
    ///     Replaces the outer HTML of the existing element.
    /// </summary>
    [Description("outer")]
    Outer,

    /// <summary>
    ///     Prepends the fragment to the existing element.
    /// </summary>
    [Description("prepend")]
    Prepend,

    /// <summary>
    ///     Appends the fragment to the existing element.
    /// </summary>
    [Description("append")]
    Append,

    /// <summary>
    ///     Inserts the fragment before the existing element.
    /// </summary>
    [Description("before")]
    Before,

    /// <summary>
    ///     Inserts the fragment after the existing element.
    /// </summary>
    [Description("after")]
    After,

    /// <summary>
    ///     Upserts the attributes of the existing element.
    /// </summary>
    [Description("upsertAttributes")]
    UpsertAttributes
}