// This is auto-generated by Datastar. DO NOT EDIT.

using NetEscapades.EnumGenerators;

namespace StarFederation.Datastar.Enumerations;

/// <summary>
///     Represents the different modes of merging fragments.
/// </summary>
[EnumExtensions]
public enum FragmentMergeMode
{
    /// <summary>
    ///     Morphs the fragment into the existing element using idiomorph.
    /// </summary>
    Morph,

    /// <summary>
    ///     Replaces the inner HTML of the existing element.
    /// </summary>
    Inner,

    /// <summary>
    ///     Replaces the outer HTML of the existing element.
    /// </summary>
    Outer,

    /// <summary>
    ///     Prepends the fragment to the existing element.
    /// </summary>
    Prepend,

    /// <summary>
    ///     Appends the fragment to the existing element.
    /// </summary>
    Append,

    /// <summary>
    ///     Inserts the fragment before the existing element.
    /// </summary>
    Before,

    /// <summary>
    ///     Inserts the fragment after the existing element.
    /// </summary>
    After,

    /// <summary>
    ///     Upserts the attributes of the existing element.
    /// </summary>
    UpsertAttributes
}