# https://taskfile.dev

version: "3"

interval: 1000ms

vars:
  VERSION:
    sh: cat VERSION

tasks:
  version:
    cmds:
      - echo {{.VERSION}}

  library:
    dir: library
    requires:
      vars: [VERSION]
    sources:
      - "**/*.ts"
      - "**/*.js"
      - "**/*.json"
    generates:
      - "dist/**/*"
    cmds:
      - pnpm i
      - pnpm build

  default:
    cmds:
      - task: site
      - ./datastar-website
