-- This is auto-generated by Datastar. DO NOT EDIT.
module ServerSentEventGenerator.Constants where

import Prelude
import ServerSentEventGenerator.Class (StringLike)

-- taken from consts.ts
-- why?
-- functions must start with a lower case letter
-- I could have used a type class, but it would have required
-- a function call in front of each data constructor, so I
-- decided to just use the prefix "c"

cDatastarKey                             :: StringLike a => a
cDatastarKey                             = "datastar"
cVersion                                 :: StringLike a => a
cVersion                                 = "1.0.0-beta.3"
cVersionClientByteSize                   :: Int
cVersionClientByteSize                   = 36872
cVersionClientByteSizeGzip               :: Int
cVersionClientByteSizeGzip               = 13691
cDefaultFragmentsSettleDuration          :: Int
cDefaultFragmentsSettleDuration          = 300 -- milliseconds
cDefaultSseRetryDuration                 :: Int
cDefaultSseRetryDuration                 = 1000 -- milliseconds
cExecuteScriptAttributes                 :: StringLike a => a
cExecuteScriptAttributes                 = "type module"
cSelector                                :: StringLike a => a
cSelector                                = "selector"
cMergeMode                               :: StringLike a => a
cMergeMode                               = "mergeMode"
cSettleDuration                          :: StringLike a => a
cSettleDuration                          = "settleDuration"
cFragments                               :: StringLike a => a
cFragments                               = "fragments"
cUseViewTransition                       :: StringLike a => a
cUseViewTransition                       = "useViewTransition"
cSignals                                 :: StringLike a => a
cSignals                                 = "signals"
cOnlyIfMissing                           :: StringLike a => a
cOnlyIfMissing                           = "onlyIfMissing"
cPaths                                   :: StringLike a => a
cPaths                                   = "paths"
cScript                                  :: StringLike a => a
cScript                                  = "script"
cAttributes                              :: StringLike a => a
cAttributes                              = "attributes"
cAutoRemove                              :: StringLike a => a
cAutoRemove                              = "autoRemove"
cDefaultFragmentsUseViewTransitions      :: Bool
cDefaultFragmentsUseViewTransitions      = False
cDefaultMergeSignalsOnlyIfMissing        :: Bool
cDefaultMergeSignalsOnlyIfMissing        = False
cDefaultExecuteScriptAutoRemove          :: Bool
cDefaultExecuteScriptAutoRemove          = True
cMorph                                   :: StringLike a => a
cMorph                                   = "morph"
cInner                                   :: StringLike a => a
cInner                                   = "inner"
cOuter                                   :: StringLike a => a
cOuter                                   = "outer"
cPrepend                                 :: StringLike a => a
cPrepend                                 = "prepend"
cAppend                                  :: StringLike a => a
cAppend                                  = "append"
cBefore                                  :: StringLike a => a
cBefore                                  = "before"
cAfter                                   :: StringLike a => a
cAfter                                   = "after"
cUpsertAttributes                        :: StringLike a => a
cUpsertAttributes                        = "upsertAttributes"
cMergeFragments                          :: StringLike a => a
cMergeFragments                          = "datastar-merge-fragments"
cMergeSignals                            :: StringLike a => a
cMergeSignals                            = "datastar-merge-signals"
cRemoveFragments                         :: StringLike a => a
cRemoveFragments                         = "datastar-remove-fragments"
cRemoveSignals                           :: StringLike a => a
cRemoveSignals                           = "datastar-remove-signals"
cExecuteScript                           :: StringLike a => a
cExecuteScript                           = "datastar-execute-script"
-- Added by Henry
cData                                    :: StringLike a => a
cData                                    =  "data"
cEvent                                   :: StringLike a => a
cEvent                                   =  "event"
cEventId                                 :: StringLike a => a
cEventId                                 =  "id"
cRetryDuration                           :: StringLike a => a
cRetryDuration                           =  "retry"
cSColon                                  :: StringLike a => a
cSColon                                  =  ": "
cSpace                                   :: StringLike a => a
cSpace                                   =  " "
cDefaultSelector                         ::  StringLike a => a
cDefaultSelector                         =  ""
cDefaultEventId                          ::  StringLike a => a
cDefaultEventId                          =  ""
cDefaultOnlyIfMissing                    :: Bool
cDefaultOnlyIfMissing                    = False
cDefaultAttributes                       ::  StringLike a => a
cDefaultAttributes                       = ""