# fly.toml app configuration file generated for billioncheckboxes on 2025-05-08T15:42:59+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'datastar-dotnet-razorpages'
primary_region = 'cdg'

[build]
  build-target = 'final'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
