package starfederation.datastar.enums;

/**
 * This is auto-generated by Datastar. DO NOT EDIT.
 */
public enum EventType {

    // An event for merging HTML elements into the DOM.
    MergeElements("datastar-merge-elements"),

    // An event for merging signals.
    MergeSignals("datastar-merge-signals"),

    // An event for executing &lt;script/&gt; elements in the browser.
    ExecuteScript("datastar-execute-script");

    private final String value;

    EventType(String value) {
        this.value = value;
    }
    
    @Override
    public String toString() {
        return value;
    }
}