package starfederation.datastar.enums;

/**
 * This is auto-generated by Datastar. DO NOT EDIT.
 */
public enum FragmentMergeMode {

    // Morphs the fragment into the existing element using idiomorph.
    Morph("morph"),

    // Replaces the inner HTML of the existing element.
    Inner("inner"),

    // Replaces the outer HTML of the existing element.
    Outer("outer"),

    // Prepends the fragment to the existing element.
    Prepend("prepend"),

    // Appends the fragment to the existing element.
    Append("append"),

    // Inserts the fragment before the existing element.
    Before("before"),

    // Inserts the fragment after the existing element.
    After("after"),

    // Upserts the attributes of the existing element.
    UpsertAttributes("upsertAttributes"),

    // Removes the existing element from the DOM.
    Remove("remove");

    private final String value;

    FragmentMergeMode(String value) {
        this.value = value;
    }
    
    @Override
    public String toString() {
        return value;
    }
}