package starfederation.datastar.enums;

/**
 * This is auto-generated by Datastar. DO NOT EDIT.
 */
public enum FragmentMergeMode {

    // Morphs the fragment into the existing element using idiomorph, preserving focus and minimizing element changes.
    Outer("outer"),

    // Morphs the fragment into the innerHTML using idiomorph, preserving focus and minimizing element changes.
    Inner("inner"),

    // Replaces the outer HTML of the existing element (no morphing).
    Replace("replace"),

    // Prepends the fragment inside the existing element.
    Prepend("prepend"),

    // Appends the fragment inside the existing element.
    Append("append"),

    // Inserts the fragment before the existing element.
    Before("before"),

    // Inserts the fragment after the existing element.
    After("after"),

    // Removes the existing element from the DOM.
    Remove("remove");

    private final String value;

    FragmentMergeMode(String value) {
        this.value = value;
    }
    
    @Override
    public String toString() {
        return value;
    }
}