<?php

namespace starfederation\datastar\enums;

/**
 * This is auto-generated by Datastar. DO NOT EDIT.
 */
enum ElementPatchMode: string
{

    // Morphs the element into the existing element using Datastar’s morphing, preserving focus and minimizing element changes.
    case Outer = 'outer';

    // Morphs the element into the innerHTML using Datastar’s morphing, preserving focus and minimizing element changes.
    case Inner = 'inner';

    // Removes the existing element from the DOM.
    case Remove = 'remove';

    // Prepends the element inside the existing element.
    case Prepend = 'prepend';

    // Appends the element inside the existing element.
    case Append = 'append';

    // Inserts the element before the existing element.
    case Before = 'before';

    // Inserts the element after the existing element.
    case After = 'after';

    // Do not morph, simply replace the whole element and reset any related state.
    case Replace = 'replace';
}