<?php

namespace starfederation\datastar\enums;

/**
 * This is auto-generated by Datastar. DO NOT EDIT.
 */
enum EventType: string
{

    // An event for merging HTML elements into the DOM.
    case MergeElements = 'datastar-merge-elements';

    // An event for merging signals.
    case MergeSignals = 'datastar-merge-signals';

    // An event for executing &lt;script/&gt; elements in the browser.
    case ExecuteScript = 'datastar-execute-script';
}