// This is auto-generated by Datastar. DO NOT EDIT.

namespace Starfederation.Datastar
{
    /// <summary>
    /// Represents the different modes of merging fragments.
    /// </summary>
    public enum FragmentMergeMode
    {
        /// <summary>
        /// Morphs the fragment into the existing element using idiomorph.
        /// </summary>
        Morph,
        
        /// <summary>
        /// Replaces the inner HTML of the existing element.
        /// </summary>
        Inner,
        
        /// <summary>
        /// Replaces the outer HTML of the existing element.
        /// </summary>
        Outer,
        
        /// <summary>
        /// Prepends the fragment to the existing element.
        /// </summary>
        Prepend,
        
        /// <summary>
        /// Appends the fragment to the existing element.
        /// </summary>
        Append,
        
        /// <summary>
        /// Inserts the fragment before the existing element.
        /// </summary>
        Before,
        
        /// <summary>
        /// Inserts the fragment after the existing element.
        /// </summary>
        After,
        
        /// <summary>
        /// Upserts the attributes of the existing element.
        /// </summary>
        UpsertAttributes
    }

    /// <summary>
    /// Represents the different types of events.
    /// </summary>
    public enum EventType
    {
        /// <summary>
        /// An event for merging HTML fragments into the DOM.
        /// </summary>
        MergeFragments,
        
        /// <summary>
        /// An event for merging signals.
        /// </summary>
        MergeSignals,
        
        /// <summary>
        /// An event for removing HTML fragments from the DOM.
        /// </summary>
        RemoveFragments,
        
        /// <summary>
        /// An event for removing signals.
        /// </summary>
        RemoveSignals,
        
        /// <summary>
        /// An event for executing &lt;script/&gt; elements in the browser.
        /// </summary>
        ExecuteScript
    }
}
