[package]
edition = "2021"
name = "hello_world"
version = "0.1.0"

[dependencies]
datastar = { path = "../../../../sdk/rust", features = ["axum"] }
rocket = { version = "0.5.1", features = ["json"] }
