name: Java SDK Unit Tests

on:
  pull_request:
    paths:
      - 'sdk/java/**'
      
jobs:
  test-java:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sdk/java
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and run tests

        run: mvn --batch-mode verify

