name: Run Tests

on:
  push:
    branches:
      - develop
    paths:
      - 'bundles/*.js'
      - 'library/src/**/*.ts'
      - 'site/smoketests/*.go'
      - 'site/static/md/tests/*.md'
      - '.github/workflows/tests.yml'
  pull_request:
  workflow_dispatch:
jobs:
  enforce-branch-policy:
    runs-on: ubuntu-latest
    steps:
      - name: Check target branch
        if: github.event.pull_request.base.ref == 'main'
        run: |
          echo "Pull requests to the main branch are not allowed."
          exit 1
      - name: Check passed
        if: github.event.pull_request.base.ref == 'develop'
        run: echo "Pull request target branch is allowed."

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run CI tests
        run: |
          docker container run --rm -t -v "${{ github.workspace }}":/app -v go-modules:/go/pkg/mod ghcr.io/starfederation/datastar-dev -c 'task tools'
          docker container run --rm -t -v "${{ github.workspace }}":/app -v go-modules:/go/pkg/mod ghcr.io/starfederation/datastar-dev -c 'task test'
